sudo: false
language: cpp
cache: apt

notifications:
    email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise # latest

matrix:
  include:
    - os: linux
      compiler: clang-3.6
      before_install:
        - |
          export CC="/usr/lib/llvm-3.6/bin/clang"
          export CXX="/usr/lib/llvm-3.6/bin/clang++"
    - os: linux
      compiler: clang-3.7
      before_install:
        - |
          export CC="/usr/lib/llvm-3.7/bin/clang"
          export CXX="/usr/lib/llvm-3.7/bin/clang++"
    - os: linux
      compiler: clang-3.8
      before_install:
        - |
          export CC="/usr/lib/llvm-3.8/bin/clang"
          export CXX="/usr/lib/llvm-3.8/bin/clang++"
    - os: linux
      compiler: gcc-4.9
      before_install:
        - |
          export CC="/usr/bin/gcc-4.9"
          export CXX="/usr/bin/g++-4.9"
    - os: linux
      compiler: gcc-5
      before_install:
        - |
          export CC="/usr/bin/gcc-5"
          export CXX="/usr/bin/g++-5"

before_script:
  cmake .

script:
  make VERBOSE=1

branches:
    only:
        - master
