sudo: false

cache: apt

notifications:
    email: false

addons:
  apt:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise # latest
    - cmake
    - build_essential

matrix:
  include:
    - os: linux
      compiler: clang-3.6
    - os: linux
      compiler: clang-3.7
    - os: linux
      compiler: clang-3.8
    - os: linux
      compiler: gcc-4.9
    - os: linux
      compiler: gcc-5.0

before_script:
  cmake .

script:
  make VERBOSE=1
branches:
    only:
        - master
