version: 1.0.{build}-{branch}

branches:
  only:
    - master

skip_tags: true
os: Visual Studio 2015

configuration:
  - Debug
  - Release

clone_folder: c:\projects\yzw2v

build:
  - project INSTALL.vcxproj

install:
  - git submodule update --init --recursive

build_script:
  - |
    cd c:\projects\yzw2v
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    cmake -G "Visual Studio 14 Win64" .
    msbuild yzw2v.sln /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
